version: "2"
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://127.0.0.1/
